apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: mavenwebappds
spec:
  selector:
    matchLabels:
      app: mavenwebapp
  template:
      metadata:
        name: mavenwebapppod
        labels:
          app: mavenwebapp
      spec:
        containers:
        - name: mavenwebappcontainer
          image: atecprojects/maven-web-application:12
          ports:
            - containerPort: 8080
---
              apiVersion: v1
              kind: Service
              metadata:
                name: mavenwebappservice
              spec:
                type: NodePort
                selector:
                  app: mavenwebapp
                ports:
                - port: 80
                  targetPort: 8080
