apiVersion: apps/v1
kind: Deployment
metadata:
  name: ridersappdeployment
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 30
  selector:
    matchLabels:
      app: ridersapp
  template:
    metadata:
      name: ridersapppod
      labels:
        app: ridersapp
    spec:
      containers:
      - name: ridersappcontainer
        image: atecprojects/riders-application:5
        ports:
        - containerPort: 8080
---
        apiVersion: v1
        kind: Service
        metadata:
          name: ridersappservice
        spec:
          type: NodePort
          selector:
            app: ridersapp
          ports:
          - port: 80
            targetPort: 8080
