apiVersion: v1
kind: ReplicationController
metadata:
  name: ridersapprc
spec:
  replicas: 2
  selector:
    app: ridersapp
  template:
    metadata:
      name: ridersapppod
      labels:
        app: ridersapp
    spec:
      containers:
      - name: ridersappcontainer
        image: atecprojects/riders-application:4
        ports:
        - containerPort: 8080
---
              apiVersion: v1
              kind: Service
              metadata:
                name: ridersappservice
              spec:
                type: NodePort
                selector:
                  app: ridersapp
                ports:
                - port: 80
                  targetPort: 8080

