apiVersion: apps/v1
kind: Deployment
metadata:
  name: springappdeployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springapp
  template:
    metadata:
      name: springapppod
      labels:
        app: springapp
    spec:
      containers:
      - name: springappcontainer
        image: atecprojects/spring-boot-mongo-docker:1
        ports:
        - containerPort: 8080
        env:
        - name: MONGO_DB_USERNAME
          value: mongodevdb
        - name: MONGO_DB_PASSWORD
          value: dev@123
        - name: MONGO_DB_HOSTNAME
          value: mongodb
---
          apiVersion: v1
          kind: Service
          metadata:
            name: springapp
          spec:
            selector:
              app: springapp
            ports:
            - port: 80
              targetPort: 8080
            type: NodePort
---
            apiVersion: apps/v1
            kind: ReplicaSet
            metadata:
              name: mongodbrs
            spec:
              selector:
                matchLabels:
                  app: mongodb
              template:
                metadata:
                  name: mongodbpod
                  labels:
                    app: mongodb
                spec:
                  containers:
                  - name: mongodbcontainer
                    image: mongo
                    ports:
                    - containerPort: 27017
                    env:
                    - name: MONGO_INITDB_ROOT_USERNAME
                      value: mongodevdb
                    - name: MONGO_INITDB_ROOT_PASSWORD
                      value: dev@123
---
                      apiVersion: v1
                      kind: Service
                      metadata:
                        name: mongodb
                      spec:
                        type: ClusterIP
                        selector:
                          app: mongodb
                        ports:
                        - port: 27017
                          targetPort: 27017
